apiVersion: policy.karmada.io/v1alpha1
kind: ClusterPropagationPolicy
metadata:
  name: knative-crds
spec:
  resourceSelectors:
    - apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: certificates.networking.internal.knative.dev
    - apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: clusterdomainclaims.networking.internal.knative.dev
    - apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: configurations.serving.knative.dev
    - apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: domainmappings.serving.knative.dev
    - apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: images.caching.internal.knative.dev
    - apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: ingresses.networking.internal.knative.dev
    - apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: metrics.autoscaling.internal.knative.dev
    - apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: podautoscalers.autoscaling.internal.knative.dev
    - apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: revisions.serving.knative.dev
    - apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: routes.serving.knative.dev
    - apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: serverlessservices.networking.internal.knative.dev
    - apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: services.serving.knative.dev
  placement:
    clusterAffinity:
      clusterNames:
        - member1
        - member2
