apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy
metadata:
  name: istio-components
  namespace: istio-system
spec:
  resourceSelectors:
    # Deployments
    - apiVersion: apps/v1
      kind: Deployment
      name: istio-ingressgateway
    - apiVersion: apps/v1
      kind: Deployment
      name: istiod
    # Services
    - apiVersion: v1
      kind: Service
      name: istio-ingressgateway
    - apiVersion: v1
      kind: Service
      name: istiod
    # ServiceAccounts
    - apiVersion: v1
      kind: ServiceAccount
      name: istio-ingressgateway-service-account
    - apiVersion: v1
      kind: ServiceAccount
      name: istio-reader-service-account
    - apiVersion: v1
      kind: ServiceAccount
      name: istiod
    # ConfigMaps
    - apiVersion: v1
      kind: ConfigMap
      name: istio
    - apiVersion: v1
      kind: ConfigMap
      name: istio-sidecar-injector
    # Roles and RoleBindings
    - apiVersion: rbac.authorization.k8s.io/v1
      kind: Role
      name: istio-ingressgateway-sds
    - apiVersion: rbac.authorization.k8s.io/v1
      kind: Role
      name: istiod
    - apiVersion: rbac.authorization.k8s.io/v1
      kind: RoleBinding
      name: istio-ingressgateway-sds
    - apiVersion: rbac.authorization.k8s.io/v1
      kind: RoleBinding
      name: istiod
    # HorizontalPodAutoscalers
    - apiVersion: autoscaling/v2
      kind: HorizontalPodAutoscaler
      name: istiod
    # PodDisruptionBudgets
    - apiVersion: policy/v1
      kind: PodDisruptionBudget
      name: istio-ingressgateway
    - apiVersion: policy/v1
      kind: PodDisruptionBudget
      name: istiod
  placement:
    clusterAffinity:
      clusterNames:
        - member1
        - member2
